<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Role;

/**
 * Base roles from docs/ARCHITECTURE.md section 7 (Security Architecture).
 * Fine-grained permissions per resource are generated by Filament Shield
 * (`php artisan shield:generate`) as Filament Resources are added in later phases.
 */
class RoleSeeder extends Seeder
{
    public function run(): void
    {
        foreach (['super_admin', 'admin', 'editor', 'author'] as $role) {
            Role::findOrCreate($role, 'web');
        }
    }
}
